### ISSUE TITLE
Bug saving the tag

### ISSUE THREAD

**Issue by danibondarchuk** [gtm-server/json-http-request-tag#1]
Successfully installed the template in my GTM. However, when creating a new tag, I select the template, enter the URL, specify the trigger, and then trying to save the tag but it's not letting me to do so. There are no errors displayed in the frontend. 
Please see the screen recording using the following link: https://drive.google.com/file/d/1uvpkQeWRfAgy4wq4Am67yTSmi_KUMXhd/view?usp=sharing

**Comment by Bukashk0zzz** [comment]
You try to use this template with GTM Web container, but it for GTM Server Side container type. Also, now this tag is available in the community template gallery, and you don't need to install it manually.

https://tagmanager.google.com/gallery/#/owners/gtm-server/templates/json-http-request-tag
