### ISSUE TITLE
can't install plugin

### ISSUE THREAD

**Issue by Artem2710** [gtm-server/json-http-request-tag#3]
Please tell me, I'm trying to install https://tagmanager.google.com/gallery/#/owners/gtm-server/templates/json-http-request-tag via the "add to workspace" button, but I'm offered to go in and download from its templates, but it is not in the templates. How can I download it? If uploading manually I have a problem as described here https://github.com/stape-io/json-http-request-tag/issues/1

**Comment by Bukashk0zzz** [comment]
Yes, problem exactly the same you try to use this template with GTM Web container, but it for GTM Server Side container type. You can't use sGTM templates for GTM Web container.
